# application-prod.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imsdb?useSSL=false&serverTimezone=UTC
    username: your_db_user
    password: your_db_pass
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate   # use migrations for prod
    show-sql: false
